/* =============================================================================
   BUILD-DEPLOY
   Everything a real server needs that a local file:// preview never did:
   .htaccess, robots.txt, sitemap.xml and a 404 page, written into dist/.

   WHAT IS AND IS NOT GENERATED.
   The domain lives in site.config.json and nowhere else. While it is empty,
   the domain-dependent outputs — canonical, og:url, hreflang, sitemap.xml —
   are SKIPPED and reported, not emitted with a placeholder. A canonical
   pointing at the wrong host is worse than no canonical at all: it actively
   tells search engines the real page is somewhere else.

   Run as part of:  node build.js
   ============================================================================= */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const DIST = path.join(ROOT, 'dist');

const cfg = JSON.parse(fs.readFileSync(path.join(ROOT, 'site.config.json'), 'utf8'));
const URL = String(cfg.url || '').replace(/\/+$/, '');

/* --- .htaccess -------------------------------------------------------------
   Hostinger shared hosting runs LiteSpeed, which reads Apache directives.
   Compression is the single biggest win here and the reason this file exists:
   the pages are 257-413KB of markup and gzip to 97-116KB, because inlined CSS,
   JS and base64 fonts compress extremely well. Served uncompressed that is
   roughly 4x the bytes for no reason.

   Every block is wrapped in <IfModule> so a host without that module ignores
   it rather than returning a 500. */
const HTACCESS = `# =============================================================================
# Pixora — server configuration
# Generated by tools/build-deploy.js. Edit the generator, not this file.
#
# Hostinger runs LiteSpeed, which reads Apache directives. Every block is
# guarded by <IfModule> so a server without the module ignores it instead of
# returning a 500.
# =============================================================================

# --- Compression -------------------------------------------------------------
# The reason this file exists. These pages inline their CSS, JS and fonts, so
# they are large and highly compressible: 413KB -> 116KB for the homepage.
<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css
  AddOutputFilterByType DEFLATE application/javascript application/json
  AddOutputFilterByType DEFLATE image/svg+xml
  # woff2 is already compressed — compressing it again costs CPU and saves
  # nothing, so it is deliberately absent.
</IfModule>

<IfModule mod_brotli.c>
  AddOutputFilterByType BROTLI_COMPRESS text/html text/css application/javascript
  AddOutputFilterByType BROTLI_COMPRESS application/json image/svg+xml
</IfModule>

# --- Caching -----------------------------------------------------------------
# The HTML carries everything, so it must never be cached hard: a stale copy is
# a stale SITE, not a stale stylesheet. One hour, revalidated.
<IfModule mod_expires.c>
  ExpiresActive On
  ExpiresByType text/html "access plus 1 hour"
  ExpiresByType image/svg+xml "access plus 1 month"
  ExpiresByType font/woff2 "access plus 1 year"
  ExpiresByType image/png "access plus 1 month"
  ExpiresByType image/jpeg "access plus 1 month"
</IfModule>

<IfModule mod_headers.c>
  <FilesMatch "\\.html$">
    Header set Cache-Control "public, max-age=3600, must-revalidate"
  </FilesMatch>

  # --- Security ---------------------------------------------------------
  Header set X-Content-Type-Options "nosniff"
  Header set Referrer-Policy "strict-origin-when-cross-origin"
  # The site sets no permissions-requiring features; deny them all.
  Header set Permissions-Policy "camera=(), microphone=(), geolocation=(), interest-cohort=()"
  # HSTS is deliberately NOT set here. Turn it on only once HTTPS is confirmed
  # working on the live domain — a bad HSTS header locks visitors out of a site
  # that cannot yet serve TLS, and the header is cached by the browser.
</IfModule>

# --- Character encoding ------------------------------------------------------
AddDefaultCharset UTF-8

# --- Error page --------------------------------------------------------------
ErrorDocument 404 /404.html

# --- Canonical host ----------------------------------------------------------
# HTTPS redirect. Hostinger issues a free certificate; enable it in hPanel
# BEFORE uploading this, or the redirect will loop for visitors on http.
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteCond %{HTTPS} !=on
  RewriteCond %{HTTP:X-Forwarded-Proto} !https
  RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

  # Serve /story for /story.html, without breaking the .html links already in
  # the markup.
  RewriteCond %{REQUEST_FILENAME}.html -f
  RewriteCond %{REQUEST_URI} !\\.html$
  RewriteRule ^(.+)$ $1.html [L]
</IfModule>

# --- Directory listing -------------------------------------------------------
Options -Indexes
`;

/* --- robots.txt ------------------------------------------------------------ */
const robots = () => {
  const blocked = cfg.pages.filter((p) => p.index === false);
  return `# Pixora
User-agent: *
Allow: /
${blocked.map((p) => `Disallow: /${p.file}`).join('\n')}
${URL ? `\nSitemap: ${URL}/sitemap.xml\n` : `
# Sitemap line is written once site.config.json carries the domain.
`}`;
};

/* --- sitemap.xml ----------------------------------------------------------- */
const sitemap = (stamp) => `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${cfg.pages.filter((p) => p.index !== false).map((p) => {
  const loc = `${URL}/${p.file === 'index.html' ? '' : p.file}`;
  return `  <url>
    <loc>${loc}</loc>
    <lastmod>${stamp}</lastmod>
    <changefreq>${p.changefreq || 'monthly'}</changefreq>
    <priority>${p.priority || '0.5'}</priority>
  </url>`;
}).join('\n')}
</urlset>
`;

/* --- Canonical + og:url ----------------------------------------------------
   Written into the BUILT pages, not the source, so the modular files stay
   host-agnostic and a change of domain is a rebuild rather than an edit.

   NO HREFLANG, deliberately. hreflang describes a set of URLs, one per
   language. This site serves English and Arabic from the SAME url and swaps
   them client-side, so there is no second URL to point at — emitting
   /ar/ alternates would advertise pages that do not exist. Separate language
   URLs would be a real architectural change, worth doing if Arabic search
   traffic matters, and not something a deploy script should fake. */
function injectHead(stamp) {
  if (!URL) return 0;
  let n = 0;
  for (const page of cfg.pages) {
    const file = path.join(DIST, page.file);
    if (!fs.existsSync(file)) continue;
    let html = fs.readFileSync(file, 'utf8');

    // Idempotent: strip what a previous run wrote before writing it again.
    html = html.replace(/\n?\s*<link rel="canonical"[^>]*>/g, '')
      .replace(/\n?\s*<meta property="og:url"[^>]*>/g, '');

    const loc = `${URL}/${page.file === 'index.html' ? '' : page.file}`;
    const tags = page.index === false
      ? '' // noindex pages get no canonical: there is nothing to canonicalise to.
      : `\n    <link rel="canonical" href="${loc}" />\n    <meta property="og:url" content="${loc}" />`;

    if (tags) {
      html = html.replace('</head>', `${tags}\n  </head>`);
      n++;
    }
    fs.writeFileSync(file, html);
  }
  return n;
}

/* --- Write ----------------------------------------------------------------- */
function run(stamp) {
  const out = [];
  fs.writeFileSync(path.join(DIST, '.htaccess'), HTACCESS);
  out.push('.htaccess');
  fs.writeFileSync(path.join(DIST, 'robots.txt'), robots());
  out.push('robots.txt');

  if (URL) {
    fs.writeFileSync(path.join(DIST, 'sitemap.xml'), sitemap(stamp));
    out.push('sitemap.xml');
    const n = injectHead(stamp);
    out.push(`canonical + og:url on ${n} page(s)`);
  }

  console.log(`deploy files -> dist/  (${out.join(', ')})`);
  if (!URL) {
    console.log('');
    console.log('  ! No domain set, so these were NOT written:');
    console.log('      sitemap.xml, <link rel="canonical">, og:url, hreflang alternates');
    console.log('    They are skipped rather than guessed — a canonical pointing at the');
    console.log('    wrong host tells search engines the real page is somewhere else.');
    console.log('    Set "url" in site.config.json and re-run.');
  }
  return { wrote: out, hasUrl: !!URL };
}

module.exports = { run, URL, cfg };
