/* =============================================================================
   BUILD-DEPLOY
   Everything a real server needs that a local file:// preview never did:
   .htaccess, robots.txt, sitemap.xml and a 404 page, written into dist/.

   WHAT IS AND IS NOT GENERATED.
   The domain lives in site.config.json and nowhere else. While it is empty,
   the domain-dependent outputs — canonical, og:url, hreflang, sitemap.xml —
   are SKIPPED and reported, not emitted with a placeholder. A canonical
   pointing at the wrong host is worse than no canonical at all: it actively
   tells search engines the real page is somewhere else.

   Run as part of:  node build.js
   ============================================================================= */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const DIST = path.join(ROOT, 'dist');
/* The deployment's own manifest, so robots.txt cannot name a page the upload
   does not contain. One list, two consumers. */
const { SHIP } = require('./build-zip');

/* THE PUBLIC FORM OF A URL. The .htaccess rewrite serves pricing.html at
   /pricing, so /pricing is the address this site has — and the canonical, the
   og:url and the sitemap must all say the same one. Two spellings of a page
   that both answer is how duplicate content happens; the extension is the
   implementation detail, not the address. Exported so qa.js asserts against
   the same rule rather than a copy of it. */
const publicPath = (file) => (file === 'index.html' ? '' : file.replace(/\.html$/, ''));

const cfg = JSON.parse(fs.readFileSync(path.join(ROOT, 'site.config.json'), 'utf8'));
const URL = String(cfg.url || '').replace(/\/+$/, '');

/* --- .htaccess -------------------------------------------------------------
   Hostinger shared hosting runs LiteSpeed, which reads Apache directives.
   Compression is the single biggest win here and the reason this file exists:
   the pages are 257-413KB of markup and gzip to 97-116KB, because inlined CSS,
   JS and base64 fonts compress extremely well. Served uncompressed that is
   roughly 4x the bytes for no reason.

   Every block is wrapped in <IfModule> so a host without that module ignores
   it rather than returning a 500. */
const htaccess = (csp) => `# =============================================================================
# Pixora — server configuration
# Generated by tools/build-deploy.js. Edit the generator, not this file.
#
# Hostinger runs LiteSpeed, which reads Apache directives. Every block is
# guarded by <IfModule> so a server without the module ignores it instead of
# returning a 500.
# =============================================================================

# --- Compression -------------------------------------------------------------
# The reason this file exists. These pages inline their CSS, JS and fonts, so
# they are large and highly compressible: 413KB -> 116KB for the homepage.
<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css
  AddOutputFilterByType DEFLATE application/javascript application/json
  AddOutputFilterByType DEFLATE image/svg+xml
  # woff2 is already compressed — compressing it again costs CPU and saves
  # nothing, so it is deliberately absent.
</IfModule>

<IfModule mod_brotli.c>
  AddOutputFilterByType BROTLI_COMPRESS text/html text/css application/javascript
  AddOutputFilterByType BROTLI_COMPRESS application/json image/svg+xml
</IfModule>

# --- Caching -----------------------------------------------------------------
# The HTML carries everything, so it must never be cached hard: a stale copy is
# a stale SITE, not a stale stylesheet. One hour, revalidated.
<IfModule mod_expires.c>
  ExpiresActive On
  ExpiresByType text/html "access plus 1 hour"
  ExpiresByType image/svg+xml "access plus 1 month"
  ExpiresByType font/woff2 "access plus 1 year"
  ExpiresByType image/png "access plus 1 month"
  ExpiresByType image/jpeg "access plus 1 month"
</IfModule>

<IfModule mod_headers.c>
  <FilesMatch "\\.html$">
    Header set Cache-Control "public, max-age=3600, must-revalidate"
  </FilesMatch>

  # --- Security ---------------------------------------------------------
  Header set X-Content-Type-Options "nosniff"
  Header set Referrer-Policy "strict-origin-when-cross-origin"
  # The site sets no permissions-requiring features; deny them all.
  Header set Permissions-Policy "camera=(), microphone=(), geolocation=(), interest-cohort=()"

  # --- Content Security Policy ------------------------------------------
  # Written by the build, not by hand, because the script hashes below change
  # whenever the JavaScript does. Every page inlines its own module, so the
  # policy names each one by hash: no 'unsafe-inline' for scripts, and a
  # tampered script simply does not run.
  #
  # style-src keeps 'unsafe-inline'. The markup carries style ATTRIBUTES
  # (--i: 0 on animated list items), which hashes cannot cover — that needs
  # 'unsafe-hashes', which is worse than what it buys. Scripts are where the
  # risk is, and scripts are locked.
  #
  # plausible.io appears twice: script-src to load the tag, connect-src for
  # the event it sends. Nothing else off-origin is permitted at all.
  Header set Content-Security-Policy "${csp}"
${cfg.hsts
    ? '  # HSTS: enabled in site.config.json AFTER the live site was verified.\n'
      + '  # The apex only. includeSubDomains would force HTTPS on every subdomain of\n'
      + '  # this host — webmail, cpanel, anything a control panel creates later — and\n'
      + '  # any one of them that cannot answer over TLS becomes unreachable for a\n'
      + '  # year. Set "hsts": "all" once every subdomain is confirmed to serve HTTPS.\n'
      + `  Header always set Strict-Transport-Security "max-age=31536000${cfg.hsts === 'all' ? '; includeSubDomains' : ''}"`
    : '  # HSTS is off: `hsts` is false in site.config.json. Turn it on there — not\n'
      + '  # here — once the live site is confirmed serving TLS. The header is cached\n'
      + '  # by browsers for a year, so switching it on too early locks visitors out\n'
      + '  # of a site that cannot answer, rather than merely inconveniencing them.'}
</IfModule>

# --- Character encoding ------------------------------------------------------
AddDefaultCharset UTF-8

# --- Error page --------------------------------------------------------------
ErrorDocument 404 /404.html

# --- Canonical host ----------------------------------------------------------
# HTTPS redirect. Hostinger issues a free certificate; enable it in hPanel
# BEFORE uploading this, or the redirect will loop for visitors on http.
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteCond %{HTTPS} !=on
  RewriteCond %{HTTP:X-Forwarded-Proto} !https
  RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

  # Serve /story for /story.html, without breaking the .html links already in
  # the markup.
  RewriteCond %{REQUEST_FILENAME}.html -f
  RewriteCond %{REQUEST_URI} !\\.html$
  RewriteRule ^(.+)$ $1.html [L]
</IfModule>

# --- Directory listing -------------------------------------------------------
Options -Indexes
`;

/* --- robots.txt ------------------------------------------------------------ */
const robots = () => {
  /* Only pages the upload actually contains. dist/ is not the deployment —
     styleguide.html is built there and deliberately left out of the archive —
     so a Disallow keyed on dist/ names a file no crawler will ever find, and
     tells anyone reading robots.txt that the site has a page it does not have. */
  const blocked = cfg.pages
    .filter((p) => p.index === false && SHIP.includes(p.file))
    .map((p) => `Disallow: /${p.file}`);

  const lines = ['# Pixora', 'User-agent: *', 'Allow: /', ...blocked, ''];
  lines.push(URL
    ? `Sitemap: ${URL}/sitemap.xml`
    : '# Sitemap line is written once site.config.json carries the domain.');
  return `${lines.join('\n')}\n`;
};

/* --- sitemap.xml ----------------------------------------------------------- */
const sitemap = (stamp) => `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${cfg.pages.filter((p) => p.index !== false).map((p) => {
  const loc = `${URL}/${publicPath(p.file)}`;
  return `  <url>
    <loc>${loc}</loc>
    <lastmod>${stamp}</lastmod>
    <changefreq>${p.changefreq || 'monthly'}</changefreq>
    <priority>${p.priority || '0.5'}</priority>
  </url>`;
}).join('\n')}
</urlset>
`;

/* --- Canonical + og:url ----------------------------------------------------
   Written into the BUILT pages, not the source, so the modular files stay
   host-agnostic and a change of domain is a rebuild rather than an edit.

   NO HREFLANG, deliberately. hreflang describes a set of URLs, one per
   language. This site serves English and Arabic from the SAME url and swaps
   them client-side, so there is no second URL to point at — emitting
   /ar/ alternates would advertise pages that do not exist. Separate language
   URLs would be a real architectural change, worth doing if Arabic search
   traffic matters, and not something a deploy script should fake. */
/* ORGANIZATION SCHEMA, homepage only.
   Every field below is a fact already published on this site and checkable
   from it — the name, the founder, the address the contact section shows, the
   two profiles the verification band links to. Nothing is asserted here that a
   visitor could not confirm, which is the same rule the rest of the site is
   held to; structured data is not a place to be more confident than the page.

   Deliberately absent: aggregateRating and review (there are none),
   priceRange (it would drift from pricing.json the first time a package moves)
   and areaServed (the site says "the Gulf and Egypt", and enumerating that
   into country codes would be inventing precision). */
function orgSchema() {
  const json = {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Pixora',
    alternateName: 'بيكسورا',
    url: `${URL}/`,
    description: 'A remote studio for the Gulf and Egypt: branding, websites, social and advertising from one team, at prices published in full.',
    image: `${URL}/assets/share-card.jpg`,
    email: 'muhalabsalah@gmail.com',
    founder: { '@type': 'Person', name: 'Muhalab Salah' },
    knowsLanguage: ['en', 'ar'],
    sameAs: [
      'https://www.behance.net/MuhalabSalah',
      'https://www.linkedin.com/in/muhalabsalah/',
    ],
  };
  return `\n    <script type="application/ld+json">${JSON.stringify(json)}</script>`;
}

function injectHead(stamp) {
  if (!URL) return 0;
  let n = 0;
  for (const page of cfg.pages) {
    const file = path.join(DIST, page.file);
    if (!fs.existsSync(file)) continue;
    let html = fs.readFileSync(file, 'utf8');

    // Idempotent: strip what a previous run wrote before writing it again.
    html = html.replace(/\n?\s*<link rel="canonical"[^>]*>/g, '')
      .replace(/\n?\s*<meta property="og:url"[^>]*>/g, '')
      .replace(/\n?\s*<meta property="og:image[^>]*>/g, '')
      .replace(/\n?\s*<meta name="twitter:[^>]*>/g, '')
      .replace(/\n?\s*<script type="application\/ld\+json">[\s\S]*?<\/script>/g, '');

    const loc = `${URL}/${publicPath(page.file)}`;

    /* THE SHARE CARD. Absolute, always — a relative og:image is ignored by
       every scraper, and the one that matters most here is WhatsApp's: this
       business converts on WhatsApp, so a link with no preview image is a grey
       strip with a domain in it, which is what a broken site looks like.
       Dimensions are declared so a previewer can lay out the card before it has
       finished fetching the image. */
    const card = `${URL}/assets/share-card.jpg`;
    const share = page.index === false ? '' : [
      `<meta property="og:image" content="${card}" />`,
      `<meta property="og:image:width" content="1200" />`,
      `<meta property="og:image:height" content="630" />`,
      `<meta property="og:image:alt" content="Pixora — your brand, your digital presence, one partner" />`,
      `<meta name="twitter:card" content="summary_large_image" />`,
      `<meta name="twitter:image" content="${card}" />`,
    ].map((t) => `\n    ${t}`).join('');

    const tags = page.index === false
      ? '' // noindex pages get no canonical: there is nothing to canonicalise to.
      : `\n    <link rel="canonical" href="${loc}" />\n    <meta property="og:url" content="${loc}" />${share}${page.file === 'index.html' ? orgSchema() : ''}`;

    if (tags) {
      html = html.replace('</head>', `${tags}\n  </head>`);
      n++;
    }
    fs.writeFileSync(file, html);
  }
  return n;
}

/* ANALYTICS — injected only when site.config.json names a provider.

   The site inlines everything it needs, so this is the one outbound request it
   will make, and it is opt-in for that reason. Idempotent like injectHead():
   a previous run's tag is stripped before this one writes. */
function injectAnalytics() {
  const a = cfg.analytics || {};
  if (!a.provider) return 0;

  /* THE QUEUE STUB, and why it is not optional.

     The provider's tag is deferred, so it lands after the document is
     interactive. Our own events start earlier than that — a package counts as
     read after one second on screen, and a visitor can press a CTA before any
     of it arrives. Without this stub `window.plausible` is undefined at that
     moment and the event is dropped silently, which is the exact failure this
     project keeps refusing to ship.

     With it, early events queue and are sent when the script loads. If the
     script never loads — a blocker, an outage — `plausible.q` simply grows and
     nothing else notices, which is the correct behaviour for a metric. */
  const stub = '<script>window.plausible=window.plausible||function(){(window.plausible.q=window.plausible.q||[]).push(arguments)}</script>';

  const tag = a.provider === 'umami'
    ? `<script defer data-website-id="${a.websiteId}" src="${a.scriptUrl}"></script>`
    : `${stub}\n    <script defer data-domain="${a.domain}" src="${a.scriptUrl}"></script>`;

  let n = 0;
  for (const page of cfg.pages) {
    const file = path.join(DIST, page.file);
    if (!fs.existsSync(file)) continue;
    let html = fs.readFileSync(file, 'utf8');
    // Strip first, on EVERY page: a page that stops being tracked has to lose
    // the tag a previous run wrote, or it goes on reporting for ever.
    html = html.replace(/\n?\s*<script>window\.plausible=[\s\S]*?<\/script>/g, '')
      .replace(/\n?\s*<script defer data-(?:domain|website-id)[^>]*><\/script>/g, '');
    // A noindex page is internal — the styleguide is read by us, and counting
    // our own visits would be the first thing to corrupt the numbers.
    if (page.index !== false) {
      html = html.replace('</head>', `    ${tag}\n  </head>`);
      n++;
    }
    fs.writeFileSync(file, html);
  }
  return n;
}

/* THE POLICY, derived from what the pages actually contain.

   Each built page inlines one module; its sha256 goes in the policy, so the
   browser runs exactly the script this build produced and nothing else. The
   hashes are unioned across pages rather than emitted per file: a page then
   also permits its siblings' scripts, which is a rounding error next to
   'unsafe-inline' and keeps the server config to one header. */
function policy() {
  const crypto = require('crypto');
  const hashes = new Set();

  for (const page of cfg.pages) {
    const file = path.join(DIST, page.file);
    if (!fs.existsSync(file)) continue;
    const html = fs.readFileSync(file, 'utf8');
    for (const m of html.matchAll(/<script\b(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi)) {
      hashes.add(`'sha256-${crypto.createHash('sha256').update(m[1], 'utf8').digest('base64')}'`);
    }
  }

  const analytics = (cfg.analytics || {}).provider ? ' https://plausible.io' : '';
  return [
    "default-src 'self'",
    "base-uri 'self'",
    "object-src 'none'",
    "frame-ancestors 'self'",
    // The contact form submits to a mailto:, which is a form action.
    "form-action 'self' mailto:",
    "img-src 'self' data:",
    "font-src 'self' data:",
    "style-src 'self' 'unsafe-inline'",
    `script-src 'self'${analytics} ${[...hashes].join(' ')}`,
    `connect-src 'self'${analytics}`,
  ].join('; ');
}

/* --- Write ----------------------------------------------------------------- */
function run(stamp) {
  const out = ['.htaccess'];
  fs.writeFileSync(path.join(DIST, 'robots.txt'), robots());
  out.push('robots.txt');

  if (URL) {
    fs.writeFileSync(path.join(DIST, 'sitemap.xml'), sitemap(stamp));
    out.push('sitemap.xml');
    const n = injectHead(stamp);
    out.push(`canonical + og:url on ${n} page(s)`);
  }

  const an = injectAnalytics();
  if (an) {
    out.push(`${cfg.analytics.provider} on ${an} page(s)`);
  } else {
    out.push('analytics OFF (no provider in site.config.json — events are collected, nothing is sent)');
  }

  /* LAST, deliberately. The CSP names every inline script by hash, so it can
     only be written once the pages are final — including the analytics stub
     injected a few lines above. Writing it first would produce a policy that
     forbids a script this same build had just added. */
  fs.writeFileSync(path.join(DIST, '.htaccess'), htaccess(policy()));

  console.log(`deploy files -> dist/  (${out.join(', ')})`);
  if (!URL) {
    console.log('');
    console.log('  ! No domain set, so these were NOT written:');
    console.log('      sitemap.xml, <link rel="canonical">, og:url, hreflang alternates');
    console.log('    They are skipped rather than guessed — a canonical pointing at the');
    console.log('    wrong host tells search engines the real page is somewhere else.');
    console.log('    Set "url" in site.config.json and re-run.');
  }
  return { wrote: out, hasUrl: !!URL };
}

module.exports = { run, URL, cfg, publicPath };
